// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqhEvrDSTbdUaz6YsfXf7Y1PvEWZFIRHs',
    appId: '1:64616098870:web:e1ca03438160a900f6fc97',
    messagingSenderId: '64616098870',
    projectId: 'chat-app-final-5ac2c',
    authDomain: 'chat-app-final-5ac2c.firebaseapp.com',
    storageBucket: 'chat-app-final-5ac2c.firebasestorage.app',
    measurementId: 'G-D8D4DZYL2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY0I6Pd3E3rBnOa5DaUhAZn9MH1QIL5no',
    appId: '1:64616098870:android:bab89ff2e25c9403f6fc97',
    messagingSenderId: '64616098870',
    projectId: 'chat-app-final-5ac2c',
    storageBucket: 'chat-app-final-5ac2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMjvAgz8Bj3aQOKS4Xh64miMpOVsvB9vs',
    appId: '1:64616098870:ios:ce24bb918aba7ccff6fc97',
    messagingSenderId: '64616098870',
    projectId: 'chat-app-final-5ac2c',
    storageBucket: 'chat-app-final-5ac2c.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMjvAgz8Bj3aQOKS4Xh64miMpOVsvB9vs',
    appId: '1:64616098870:ios:ce24bb918aba7ccff6fc97',
    messagingSenderId: '64616098870',
    projectId: 'chat-app-final-5ac2c',
    storageBucket: 'chat-app-final-5ac2c.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqhEvrDSTbdUaz6YsfXf7Y1PvEWZFIRHs',
    appId: '1:64616098870:web:d3355c8c65ac57eef6fc97',
    messagingSenderId: '64616098870',
    projectId: 'chat-app-final-5ac2c',
    authDomain: 'chat-app-final-5ac2c.firebaseapp.com',
    storageBucket: 'chat-app-final-5ac2c.firebasestorage.app',
    measurementId: 'G-W0ZW7RKDZJ',
  );
}
